pipeline {
    agent any
    
    stages {
        stage('Checkout helm chart') {
            steps {
                checkout scm
            }
        }
        stage('checkout private repo') {
            steps {
                    dir('private_repo') {
                    git branch: private_repo_branch, credentialsId: private_repo_credentials, url: private_repo_url
                }
             }
            }
        stage('Deploy') {
            steps {
                script {
                        jobName = sh(returnStdout: true, script: "echo $JOB_NAME").split('/')[-1].trim().toLowerCase()
                        currentWs = sh(returnStdout: true, script: 'pwd').trim()
                        envname = sh(returnStdout: true, script: "echo $JOB_NAME").split('/')[-3].trim()
                        sh "echo $envname"
                        chart_path = "${currentWs}/kubernetes/helm_charts/MyJP/$jobName"
                        values_file = "${currentWs}/private_repo/ansible/inventory/dev/EJP/private_values.yaml"
                        kubeconfig_path = sh(returnStdout: true, script: "grep kubeconfig_path $values_file").split('/')[-1].trim()
                        sh "echo $kubeconfig_path"
                        sh "helm upgrade --install $jobName $chart_path --namespace  $djp_namespace --kubeconfig  $kubeconfig_path -f $values_file"
                }
            }
        }
    }

}

